"""Evidence-first NSE equity research engine.

This package is research-only and intentionally contains no live-order execution entry point.
"""

from .costs import reconcile_costs, round_trip_result
from .experiment import (
    ApprovedCapital,
    BaselineComparisonEvidence,
    ConcretePromotionEvidence,
    CorporateActionEvidenceIdentity,
    CostModelIdentity,
    CostReconciliationEvidence,
    DataLeakageError,
    DatasetFingerprintMismatchError,
    EmbargoSpec,
    EventDrivenSimulationEvidence,
    ExperimentArtifact,
    ExperimentOrchestrator,
    ExperimentValidationError,
    FrictionScenarioSpec,
    HeldOutTestEvidence,
    LiveOrderAttemptError,
    MissingEvidenceError,
    NSEMembershipEvidenceIdentity,
    PaperTradingEvidence,
    RejectedCandidateSpec,
    ResearchWindowConfig,
    SessionPolicyIdentity,
    SlippageStressEvidence,
    StrategySpec,
    TickEvidenceIdentity,
    UniverseFingerprintMismatchError,
    WindowSpec,
    compute_prefilter_artifact_fingerprint,
)
from .gates import evaluate_promotion_gate
from .models import (
    ChargeBreakdown,
    CostQuote,
    CostSource,
    Exchange,
    ExecutionFriction,
    OrderSpec,
    Product,
    Side,
)

__all__ = [
    "ApprovedCapital",
    "BaselineComparisonEvidence",
    "ChargeBreakdown",
    "ConcretePromotionEvidence",
    "CorporateActionEvidenceIdentity",
    "CostModelIdentity",
    "CostQuote",
    "CostReconciliationEvidence",
    "CostSource",
    "DataLeakageError",
    "DatasetFingerprintMismatchError",
    "EmbargoSpec",
    "EventDrivenSimulationEvidence",
    "Exchange",
    "ExecutionFriction",
    "ExperimentArtifact",
    "ExperimentOrchestrator",
    "ExperimentValidationError",
    "FrictionScenarioSpec",
    "HeldOutTestEvidence",
    "LiveOrderAttemptError",
    "MissingEvidenceError",
    "NSEMembershipEvidenceIdentity",
    "OrderSpec",
    "PaperTradingEvidence",
    "Product",
    "RejectedCandidateSpec",
    "ResearchWindowConfig",
    "SessionPolicyIdentity",
    "Side",
    "SlippageStressEvidence",
    "StrategySpec",
    "TickEvidenceIdentity",
    "UniverseFingerprintMismatchError",
    "WindowSpec",
    "compute_prefilter_artifact_fingerprint",
    "evaluate_promotion_gate",
    "reconcile_costs",
    "round_trip_result",
]
