"""Deterministic repeated walk-forward research-window plan compiler (v2).

PLAN artifacts only. No strategy execution, no profitability computation, no
performance thresholds, no optimal window inference, no broker calls, no data
downloads, no test-data access during selection. All sizes, steps, embargoes,
minimum observations, and minimum folds are explicit caller inputs; there are
no hidden defaults.

Structure (repeated WFO + separately untouched FINAL test):

- ``folds``: deterministic repeated chronological folds generated by the shared
  :mod:`wfo_schedule` scheduler (also used by ``walk_forward``). Each fold has
  train, embargo, and validation windows. Fold validation participates in
  selection; it is never the FINAL test.
- ``final_embargo`` + ``final_test`` (role ``untouched_test``): strictly after
  every fold, never participates in model, stock, or parameter selection.

Trust model (explicit):

- Cost and corporate-action inputs are bound as *unverified claims*, never as
  verified evidence. ``CostEvidenceClaim`` mirrors ``CostEvidenceIdentity``
  fields so later convergence (a65) can verify them, but the compiler itself
  records ``verification_status="unverified-claim"`` and requires
  ``historical_actual=False``. A bare ``"0"*64`` fingerprint therefore remains
  an unverified claim; it can never be treated as verified.
- ``CorporateActionClaim`` requires a 64-character hex fingerprint, so an
  arbitrary label such as ``"claimed-ca"`` fails closed at construction.
- PIT membership is bound per instrument via :class:`PITMembershipAttestation`
  (instrument, trade dates, evidence_as_of, source fingerprint), never via one
  opaque string.
- Selection requires a full :class:`SelectionAttestation`. Arbitrary winner
  assertions are rejected. Authorizing the FINAL test requires a valid
  attestation bound into the plan.
- The experiment adapter (:meth:`ResearchWindowPlan.to_experiment_adapter`) is
  lossless: every embargo window and every explicit role is preserved. Direct
  ``ExperimentArtifact`` integration is marked blocked because that schema
  carries a single embargo integer and anonymous validation windows.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping
from dataclasses import dataclass, field
from datetime import date, datetime
from decimal import Decimal
from enum import StrEnum
from typing import Any

from .wfo_schedule import plan_wfo_date_windows

SCHEMA_VERSION = "openalgo-research-window-plan/v2"
ADAPTER_SCHEMA_VERSION = "openalgo-research-window-plan-adapter/v2"
TRUST_STATUS_UNVERIFIED = "unverified-claim"


class ResearchWindowError(ValueError):
    """Base failure for invalid research-window plans."""


class WindowTooShortError(ResearchWindowError):
    """Raised when the calendar cannot satisfy requested durations or folds."""


class WindowLeakageError(ResearchWindowError):
    """Raised when windows overlap or embargo separation is violated."""


class UntouchedTestViolationError(ResearchWindowError):
    """Raised when the FINAL test enters selection or is bypassed."""


class FrozenUniverseViolationError(ResearchWindowError):
    """Raised when the frozen population is missing, partial, or replaced."""


class AttestationError(ResearchWindowError):
    """Raised when a selection attestation is missing or invalid."""


class EvidenceClaimError(ResearchWindowError):
    """Raised when an evidence claim is malformed; claims are never verified here."""


class WindowRole(StrEnum):
    """Immutable role for one compiled window."""

    TRAIN = "train"
    VALIDATION = "validation"
    EMBARGO = "embargo"
    UNTOUCHED_TEST = "untouched_test"


def _canonical_value(value: Any) -> Any:
    if isinstance(value, Decimal):
        return str(value)
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    if isinstance(value, Mapping):
        return {
            str(k): _canonical_value(v) for k, v in sorted(value.items(), key=lambda kv: str(kv[0]))
        }
    if isinstance(value, (list, tuple)):
        return [_canonical_value(v) for v in value]
    if hasattr(value, "as_dict"):
        return _canonical_value(value.as_dict())
    if hasattr(value, "__dataclass_fields__"):
        from dataclasses import asdict as _asdict

        return _canonical_value(_asdict(value))
    return value


def canonical_json_bytes(payload: Mapping[str, Any]) -> bytes:
    """Return canonical sorted compact JSON bytes for hashing."""
    canonical = {str(k): _canonical_value(v) for k, v in sorted(payload.items())}
    return json.dumps(
        canonical,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")


def canonical_sha256(payload: Mapping[str, Any]) -> str:
    """Return hex SHA-256 over the canonical JSON payload."""
    return hashlib.sha256(canonical_json_bytes(payload)).hexdigest()


def _require_nonempty_str(name: str, value: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ResearchWindowError(f"{name} is required and must be a non-empty string")
    return value


def _require_hex_digest(name: str, value: str) -> str:
    _require_nonempty_str(name, value)
    if len(value) != 64 or any(c not in "0123456789abcdef" for c in value):
        raise ResearchWindowError(f"{name} must be a 64-character lowercase hex digest")
    return value


def _canonical_pairs(name: str, mapping: Mapping[str, str]) -> tuple[tuple[str, str], ...]:
    if not isinstance(mapping, Mapping) or not mapping:
        raise ResearchWindowError(f"{name} must be a non-empty mapping")
    items = [(str(k), str(v)) for k, v in mapping.items()]
    for key, value in items:
        if not key.strip():
            raise ResearchWindowError(f"{name} contains an empty key")
        if not value.strip():
            raise ResearchWindowError(f"{name}[{key!r}] must be a non-empty string")
    return tuple(sorted(items))


def _canonical_param_pairs(
    parameters: Mapping[str, str] | tuple[tuple[str, str], ...],
) -> tuple[tuple[str, str], ...]:
    if isinstance(parameters, Mapping):
        items = [(str(k), str(v)) for k, v in parameters.items()]
    else:
        items = [(str(k), str(v)) for k, v in tuple(parameters)]
    if not items:
        raise ResearchWindowError("parameters must not be empty")
    for key, value in items:
        if not key.strip() or not value.strip():
            raise ResearchWindowError("parameters must be non-empty strings")
    result = tuple(sorted(items))
    if len({k for k, _ in result}) != len(result):
        raise ResearchWindowError("parameters contains duplicate keys")
    return result


@dataclass(frozen=True)
class CompiledWindow:
    """One immutable chronological window slice."""

    role: WindowRole
    window_id: str
    start: date | None
    end: date | None
    trading_dates: tuple[date, ...]

    def __post_init__(self) -> None:
        if not self.window_id.strip():
            raise ResearchWindowError("window_id is required")
        if self.role is WindowRole.EMBARGO:
            if not self.trading_dates and (self.start is not None or self.end is not None):
                raise ResearchWindowError("empty embargo window must have null bounds")
            if self.trading_dates and (
                self.start != self.trading_dates[0] or self.end != self.trading_dates[-1]
            ):
                raise ResearchWindowError("embargo bounds must match its trading dates")
        else:
            if not self.trading_dates:
                raise ResearchWindowError(f"{self.role.value} window must not be empty")
            if self.start != self.trading_dates[0] or self.end != self.trading_dates[-1]:
                raise ResearchWindowError("window bounds must match its trading dates")

    def as_dict(self) -> dict[str, Any]:
        return {
            "role": self.role.value,
            "window_id": self.window_id,
            "start": self.start.isoformat() if self.start is not None else None,
            "end": self.end.isoformat() if self.end is not None else None,
            "trading_dates": [d.isoformat() for d in self.trading_dates],
            "trading_day_count": len(self.trading_dates),
        }


@dataclass(frozen=True)
class WFOFold:
    """One repeated fold: train, embargo, validation. Validation selects; FINAL test never does."""

    fold_id: str
    train: CompiledWindow
    embargo: CompiledWindow
    validation: CompiledWindow

    def __post_init__(self) -> None:
        if not self.fold_id.strip():
            raise ResearchWindowError("fold_id is required")
        if self.train.role is not WindowRole.TRAIN:
            raise ResearchWindowError("fold train must carry TRAIN role")
        if self.embargo.role is not WindowRole.EMBARGO:
            raise ResearchWindowError("fold embargo must carry EMBARGO role")
        if self.validation.role is not WindowRole.VALIDATION:
            raise ResearchWindowError("fold validation must carry VALIDATION role")

    def as_dict(self) -> dict[str, Any]:
        return {
            "fold_id": self.fold_id,
            "train": self.train.as_dict(),
            "embargo": self.embargo.as_dict(),
            "validation": self.validation.as_dict(),
        }


@dataclass(frozen=True)
class CostEvidenceClaim:
    """Unverified cost-evidence claim binding all CostEvidenceIdentity fields.

    The compiler never verifies ledger evidence; convergence performs trusted
    verification later. ``historical_actual`` must be False here, so no claim
    (including ``"0"*64``) can be treated as verified historical actuals.
    """

    ledger_schema_version: str
    ledger_fingerprint: str
    evidence_classification: str
    historical_actual: bool
    product_scope: str
    evidence_mode: str
    policy_identity: str
    resolved_on_date: date
    selected_record_ids: tuple[str, ...]
    unknown_components: tuple[str, ...]
    scenario_identity: str | None = None
    verification_status: str = TRUST_STATUS_UNVERIFIED

    def __post_init__(self) -> None:
        for name in (
            "ledger_schema_version",
            "ledger_fingerprint",
            "evidence_classification",
            "product_scope",
            "evidence_mode",
            "policy_identity",
        ):
            if not str(getattr(self, name)).strip():
                raise EvidenceClaimError(f"cost claim {name} is required")
        _require_hex_digest("cost claim ledger_fingerprint", self.ledger_fingerprint)
        if self.verification_status != TRUST_STATUS_UNVERIFIED:
            raise EvidenceClaimError("cost claim must remain an unverified claim here")
        if self.historical_actual:
            raise EvidenceClaimError(
                "cost claim historical_actual must be False; "
                "verified historical actuals require convergence verification"
            )
        for record_id in self.selected_record_ids:
            if not str(record_id).strip():
                raise EvidenceClaimError("cost claim selected_record_ids must be non-empty")

    def as_dict(self) -> dict[str, Any]:
        return {
            "ledger_schema_version": self.ledger_schema_version,
            "ledger_fingerprint": self.ledger_fingerprint,
            "evidence_classification": self.evidence_classification,
            "historical_actual": self.historical_actual,
            "product_scope": self.product_scope,
            "evidence_mode": self.evidence_mode,
            "policy_identity": self.policy_identity,
            "resolved_on_date": self.resolved_on_date.isoformat(),
            "selected_record_ids": list(self.selected_record_ids),
            "unknown_components": list(self.unknown_components),
            "scenario_identity": self.scenario_identity,
            "verification_status": self.verification_status,
        }


@dataclass(frozen=True)
class CorporateActionClaim:
    """Unverified corporate-action claim. Fingerprint must be hex; labels fail closed."""

    policy: str
    coverage: str
    population: tuple[str, ...]
    complete: bool
    fingerprint: str
    verification_status: str = TRUST_STATUS_UNVERIFIED

    def __post_init__(self) -> None:
        _require_nonempty_str("corporate-action claim policy", self.policy)
        _require_nonempty_str("corporate-action claim coverage", self.coverage)
        if not self.population:
            raise EvidenceClaimError("corporate-action claim population must not be empty")
        normalized = tuple(sorted(set(self.population)))
        if any(not str(key).strip() for key in normalized):
            raise EvidenceClaimError("corporate-action claim population keys must be non-empty")
        if normalized != self.population:
            raise EvidenceClaimError("corporate-action claim population must be sorted unique")
        if not isinstance(self.complete, bool):
            raise EvidenceClaimError("corporate-action claim completeness must be boolean")
        _require_hex_digest("corporate-action claim fingerprint", self.fingerprint)
        if self.verification_status != TRUST_STATUS_UNVERIFIED:
            raise EvidenceClaimError("corporate-action claim must remain an unverified claim here")

    def as_dict(self) -> dict[str, Any]:
        return {
            "policy": self.policy,
            "coverage": self.coverage,
            "population": list(self.population),
            "complete": self.complete,
            "fingerprint": self.fingerprint,
            "verification_status": self.verification_status,
        }


@dataclass(frozen=True)
class PITMembershipAttestation:
    """Per-instrument PIT membership attestation (never one opaque string)."""

    instrument_key: str
    trade_dates: tuple[date, ...]
    evidence_as_of: date
    source_fingerprint: str

    def __post_init__(self) -> None:
        if not self.instrument_key.strip():
            raise ResearchWindowError("PIT attestation instrument_key is required")
        if not self.trade_dates or tuple(sorted(set(self.trade_dates))) != self.trade_dates:
            raise ResearchWindowError("PIT attestation trade_dates must be sorted unique")
        _require_hex_digest("PIT attestation source_fingerprint", self.source_fingerprint)
        if self.evidence_as_of > max(self.trade_dates):
            raise WindowLeakageError(
                "PIT evidence_as_of must not be after the attested trade dates"
            )

    def as_dict(self) -> dict[str, Any]:
        return {
            "instrument_key": self.instrument_key,
            "trade_dates": [d.isoformat() for d in self.trade_dates],
            "evidence_as_of": self.evidence_as_of.isoformat(),
            "source_fingerprint": self.source_fingerprint,
        }


@dataclass(frozen=True)
class StrategyDefinitionClaim:
    """Candidate strategy definition bound into plan identity (immutable params)."""

    strategy_name: str
    parameters: tuple[tuple[str, str], ...]
    source_refs: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        _require_nonempty_str("strategy strategy_name", self.strategy_name)
        object.__setattr__(self, "parameters", _canonical_param_pairs(self.parameters))
        normalized_refs = tuple(self.source_refs)
        if any(not str(ref).strip() for ref in normalized_refs):
            raise ResearchWindowError("strategy source_refs must be non-empty strings")

    def as_dict(self) -> dict[str, Any]:
        return {
            "strategy_name": self.strategy_name,
            "parameters": [[k, v] for k, v in self.parameters],
            "source_refs": list(self.source_refs),
        }


@dataclass(frozen=True)
class FrozenTrainUniverse:
    """Frozen population with internally derived population fingerprint."""

    instruments: tuple[str, ...]
    universe_policy_id: str
    population_fingerprint: str
    frozen_as_of: date

    def __post_init__(self) -> None:
        if not self.instruments or tuple(sorted(set(self.instruments))) != self.instruments:
            raise FrozenUniverseViolationError("frozen instruments must be sorted unique")
        if any(not key.strip() for key in self.instruments):
            raise FrozenUniverseViolationError("instrument key must be non-empty")
        _require_nonempty_str("universe_policy_id", self.universe_policy_id)
        _require_hex_digest("population_fingerprint", self.population_fingerprint)

    def as_dict(self) -> dict[str, Any]:
        return {
            "instruments": list(self.instruments),
            "universe_policy_id": self.universe_policy_id,
            "population_fingerprint": self.population_fingerprint,
            "frozen_as_of": self.frozen_as_of.isoformat(),
        }


@dataclass(frozen=True)
class TrainWinner:
    """Plan-level winner with deeply immutable parameters."""

    instrument_key: str
    strategy_name: str
    parameters: tuple[tuple[str, str], ...]

    def __post_init__(self) -> None:
        if not self.instrument_key.strip():
            raise ResearchWindowError("winner instrument_key (stock) is required")
        if not self.strategy_name.strip():
            raise ResearchWindowError("winner strategy_name is required")
        object.__setattr__(self, "parameters", _canonical_param_pairs(self.parameters))

    def as_dict(self) -> dict[str, Any]:
        return {
            "instrument_key": self.instrument_key,
            "strategy_name": self.strategy_name,
            "parameters": [[k, v] for k, v in self.parameters],
        }


@dataclass(frozen=True)
class SelectionAttestation:
    """Full selection attestation. Arbitrary winner assertions are rejected."""

    plan_fingerprint: str
    selection_pipeline_id: str
    candidate_definition_fingerprint: str
    observed_selection_dates: tuple[date, ...]
    dataset_fingerprints: tuple[tuple[str, str], ...]
    strategy_definition_fingerprint: str
    parameter_grid_fingerprint: str
    ranking_artifact_fingerprint: str
    winner_instrument: str
    winner_strategy: str
    winner_parameters: tuple[tuple[str, str], ...]
    selection_dates: tuple[date, ...]

    def __post_init__(self) -> None:
        _require_hex_digest("attestation plan_fingerprint", self.plan_fingerprint)
        _require_nonempty_str("attestation selection_pipeline_id", self.selection_pipeline_id)
        for name in (
            "candidate_definition_fingerprint",
            "strategy_definition_fingerprint",
            "parameter_grid_fingerprint",
            "ranking_artifact_fingerprint",
        ):
            _require_hex_digest(f"attestation {name}", getattr(self, name))
        if not self.observed_selection_dates or tuple(
            sorted(set(self.observed_selection_dates))
        ) != tuple(self.observed_selection_dates):
            raise AttestationError("observed_selection_dates must be sorted unique")
        if not self.selection_dates or tuple(sorted(set(self.selection_dates))) != tuple(
            self.selection_dates
        ):
            raise AttestationError("selection_dates must be non-empty sorted unique")
        if not self.winner_instrument.strip():
            raise AttestationError("winner_instrument (stock) is required")
        if not self.winner_strategy.strip():
            raise AttestationError("winner_strategy is required")
        object.__setattr__(
            self,
            "dataset_fingerprints",
            tuple(sorted(tuple(pair) for pair in self.dataset_fingerprints)),
        )
        if not self.dataset_fingerprints:
            raise AttestationError("dataset_fingerprints must not be empty")
        object.__setattr__(
            self, "winner_parameters", _canonical_param_pairs(self.winner_parameters)
        )

    def fingerprint(self) -> str:
        """Deterministic attestation identity."""
        return canonical_sha256(self.as_dict())

    def as_dict(self) -> dict[str, Any]:
        return {
            "plan_fingerprint": self.plan_fingerprint,
            "selection_pipeline_id": self.selection_pipeline_id,
            "candidate_definition_fingerprint": self.candidate_definition_fingerprint,
            "observed_selection_dates": [d.isoformat() for d in self.observed_selection_dates],
            "dataset_fingerprints": [[k, v] for k, v in self.dataset_fingerprints],
            "strategy_definition_fingerprint": self.strategy_definition_fingerprint,
            "parameter_grid_fingerprint": self.parameter_grid_fingerprint,
            "ranking_artifact_fingerprint": self.ranking_artifact_fingerprint,
            "winner_instrument": self.winner_instrument,
            "winner_strategy": self.winner_strategy,
            "winner_parameters": [[k, v] for k, v in self.winner_parameters],
            "selection_dates": [d.isoformat() for d in self.selection_dates],
        }


def derive_population_fingerprint(
    *,
    instruments: tuple[str, ...],
    universe_policy_id: str,
    pit_attestations: tuple[PITMembershipAttestation, ...],
) -> str:
    """Derive the canonical population fingerprint internally (never caller-supplied)."""
    return canonical_sha256(
        {
            "instruments": list(instruments),
            "universe_policy_id": universe_policy_id,
            "pit_attestations": [item.as_dict() for item in pit_attestations],
        }
    )


@dataclass(frozen=True)
class ResearchWindowPlan:
    """Immutable repeated-WFO plan with separately untouched FINAL test."""

    schema_version: str
    research_start: date
    research_end: date
    folds: tuple[WFOFold, ...]
    final_embargo: CompiledWindow
    final_test: CompiledWindow
    fold_train_days: int
    fold_validation_days: int
    fold_step_days: int
    fold_embargo_days: int
    final_test_days: int
    final_embargo_days: int
    min_observations_per_window: int
    min_folds: int
    approved_capital_rupees: Decimal
    session_policy_id: str
    cas_policy_id: str
    cost_claim: CostEvidenceClaim
    ca_claim: CorporateActionClaim
    dataset_fingerprints: tuple[tuple[str, str], ...]
    universe_policy_id: str
    pit_attestations: tuple[PITMembershipAttestation, ...]
    frozen_train_universe: FrozenTrainUniverse
    strategy_definitions: tuple[StrategyDefinitionClaim, ...]
    selection_attestation: SelectionAttestation | None = None
    created_at: str | None = field(default=None, compare=False)

    def __post_init__(self) -> None:
        if self.schema_version != SCHEMA_VERSION:
            raise ResearchWindowError(f"unsupported schema {self.schema_version!r}")
        if self.research_start > self.research_end:
            raise ResearchWindowError("research_start must be on or before research_end")
        if len(self.folds) < 2:
            raise WindowTooShortError("repeated WFO requires at least two folds")
        if len(self.folds) < self.min_folds:
            raise WindowTooShortError(
                f"compiled {len(self.folds)} folds below required min_folds={self.min_folds}"
            )
        for fold in self.folds:
            if not isinstance(fold, WFOFold):
                raise ResearchWindowError("folds must be WFOFold records")
        if self.final_embargo.role is not WindowRole.EMBARGO:
            raise ResearchWindowError("final_embargo must carry EMBARGO role")
        if self.final_test.role is not WindowRole.UNTOUCHED_TEST:
            raise ResearchWindowError("final_test must carry UNTOUCHED_TEST role")
        # Chronology: every fold strictly before final embargo/test; folds ordered.
        seen: set[date] = set()
        ordered_windows: list[CompiledWindow] = []
        for fold in self.folds:
            ordered_windows.extend([fold.train, fold.embargo, fold.validation])
        ordered_windows.extend([self.final_embargo, self.final_test])
        for window in ordered_windows:
            overlap = seen & set(window.trading_dates)
            if window.trading_dates and overlap:
                # Folds intentionally slide (overlap across folds); only FINAL
                # regions must be disjoint from every fold.
                final_dates = set(self.final_embargo.trading_dates) | set(
                    self.final_test.trading_dates
                )
                if set(window.trading_dates) & final_dates and window not in (
                    self.final_embargo,
                    self.final_test,
                ):
                    raise WindowLeakageError("FINAL embargo/test must never overlap folds")
                continue
            seen |= set(window.trading_dates)
        final_dates = set(self.final_embargo.trading_dates) | set(self.final_test.trading_dates)
        for fold in self.folds:
            fold_dates = (
                set(fold.train.trading_dates)
                | set(fold.embargo.trading_dates)
                | set(fold.validation.trading_dates)
            )
            if fold_dates & final_dates:
                raise WindowLeakageError("FINAL test regions must be disjoint from folds")
            if fold.train.end is not None and fold.validation.start is not None:
                if fold.train.end >= fold.validation.start:
                    raise WindowLeakageError("fold train must end strictly before validation")
        if self.final_test.trading_dates and self.final_embargo.trading_dates:
            assert self.final_embargo.end is not None and self.final_test.start is not None
            if self.final_embargo.end >= self.final_test.start:
                raise WindowLeakageError("final embargo must end strictly before FINAL test")
        last_validation_end = max(
            fold.validation.end for fold in self.folds if fold.validation.end is not None
        )
        first_final_start = (
            self.final_embargo.start if self.final_embargo.trading_dates else self.final_test.start
        )
        assert last_validation_end is not None and first_final_start is not None
        if last_validation_end >= first_final_start:
            raise WindowLeakageError("every fold must end strictly before FINAL regions")
        if self.approved_capital_rupees <= Decimal(0):
            raise ResearchWindowError("approved_capital_rupees must be positive")
        dataset_keys = tuple(k for k, _ in self.dataset_fingerprints)
        if dataset_keys != self.frozen_train_universe.instruments:
            raise FrozenUniverseViolationError(
                "dataset instrument keys must exactly equal frozen train universe instruments"
            )
        attestation_keys = tuple(item.instrument_key for item in self.pit_attestations)
        if attestation_keys != self.frozen_train_universe.instruments:
            raise FrozenUniverseViolationError(
                "PIT attestations must cover exactly the frozen population"
            )
        expected_population = derive_population_fingerprint(
            instruments=self.frozen_train_universe.instruments,
            universe_policy_id=self.universe_policy_id,
            pit_attestations=self.pit_attestations,
        )
        if expected_population != self.frozen_train_universe.population_fingerprint:
            raise FrozenUniverseViolationError("population fingerprint mismatch")
        if self.selection_attestation is not None:
            self._validate_attestation(self.selection_attestation)

    def selection_union_dates(self) -> tuple[date, ...]:
        """Union of fold train+validation dates. FINAL test never included."""
        union = set()
        for fold in self.folds:
            union |= set(fold.train.trading_dates) | set(fold.validation.trading_dates)
        return tuple(sorted(union))

    def _validate_attestation(self, attestation: SelectionAttestation) -> None:
        if attestation.plan_fingerprint != self.fingerprint_without_selection():
            raise AttestationError("attestation plan_fingerprint does not match this plan")
        if tuple(attestation.observed_selection_dates) != self.selection_union_dates():
            raise AttestationError(
                "attestation observed dates must exactly equal fold train+validation union"
            )
        if tuple(attestation.dataset_fingerprints) != self.dataset_fingerprints:
            raise AttestationError(
                "attestation dataset fingerprints must exactly equal plan datasets"
            )
        if not attestation.selection_dates:
            raise AttestationError("selection_dates must be non-empty")
        allowed = set(self.selection_union_dates())
        for day in attestation.selection_dates:
            if day not in allowed:
                raise UntouchedTestViolationError(
                    f"selection date {day.isoformat()} is outside fold train+validation"
                )
        if attestation.winner_instrument not in set(self.frozen_train_universe.instruments):
            raise FrozenUniverseViolationError("attested winner is outside the frozen universe")
        defined = {item.strategy_name: item for item in self.strategy_definitions}
        if attestation.winner_strategy not in defined:
            raise AttestationError("attested winner strategy is not in plan strategy definitions")
        if tuple(attestation.winner_parameters) != defined[attestation.winner_strategy].parameters:
            raise AttestationError(
                "attested winner parameters do not match plan strategy definition"
            )

    def deterministic_payload(self) -> dict[str, Any]:
        """Canonical identity payload. Volatile created_at is excluded."""
        return {
            "schema_version": self.schema_version,
            "research_start": self.research_start.isoformat(),
            "research_end": self.research_end.isoformat(),
            "folds": [fold.as_dict() for fold in self.folds],
            "final_embargo": self.final_embargo.as_dict(),
            "final_test": self.final_test.as_dict(),
            "fold_train_days": self.fold_train_days,
            "fold_validation_days": self.fold_validation_days,
            "fold_step_days": self.fold_step_days,
            "fold_embargo_days": self.fold_embargo_days,
            "final_test_days": self.final_test_days,
            "final_embargo_days": self.final_embargo_days,
            "min_observations_per_window": self.min_observations_per_window,
            "min_folds": self.min_folds,
            "approved_capital_rupees": str(self.approved_capital_rupees),
            "session_policy_id": self.session_policy_id,
            "cas_policy_id": self.cas_policy_id,
            "cost_claim": self.cost_claim.as_dict(),
            "ca_claim": self.ca_claim.as_dict(),
            "dataset_fingerprints": [[k, v] for k, v in self.dataset_fingerprints],
            "universe_policy_id": self.universe_policy_id,
            "pit_attestations": [item.as_dict() for item in self.pit_attestations],
            "frozen_train_universe": self.frozen_train_universe.as_dict(),
            "strategy_definitions": [item.as_dict() for item in self.strategy_definitions],
            "selection_attestation": (
                self.selection_attestation.as_dict() if self.selection_attestation else None
            ),
        }

    def fingerprint_without_selection(self) -> str:
        """Fingerprint of the plan before selection binding (attestation excluded)."""
        payload = self.deterministic_payload()
        payload["selection_attestation"] = None
        return canonical_sha256(payload)

    def fingerprint(self) -> str:
        """Deterministic SHA-256 over the canonical plan payload."""
        return canonical_sha256(self.deterministic_payload())

    @property
    def plan_id(self) -> str:
        """Deterministic plan identity derived from the fingerprint."""
        return f"rwp_{self.fingerprint()[:16]}"

    def to_dict(self) -> dict[str, Any]:
        """Full representation including identity and volatile metadata."""
        payload = self.deterministic_payload()
        payload["plan_id"] = self.plan_id
        payload["fingerprint"] = self.fingerprint()
        payload["created_at"] = self.created_at
        return payload

    def to_json(self) -> str:
        """Canonical JSON with sorted keys."""
        return json.dumps(self.to_dict(), sort_keys=True, separators=(",", ":")) + "\n"

    def to_experiment_adapter(self) -> dict[str, Any]:
        """Lossless adapter preserving every embargo window and explicit role.

        Direct ``ExperimentArtifact`` integration is marked blocked: that schema
        carries one embargo integer and anonymous validation windows, which
        cannot represent N fold embargoes plus the FINAL embargo with distinct
        VALIDATION vs UNTOUCHED_TEST roles. Never collapses provenance.
        """
        return {
            "schema": ADAPTER_SCHEMA_VERSION,
            "plan_id": self.plan_id,
            "plan_fingerprint": self.fingerprint(),
            "research_window": {
                "start": self.research_start.isoformat(),
                "end": self.research_end.isoformat(),
            },
            "folds": [fold.as_dict() for fold in self.folds],
            "final_embargo": self.final_embargo.as_dict(),
            "final_test": self.final_test.as_dict(),
            "embargo_windows": [
                {"fold_id": fold.fold_id, **fold.embargo.as_dict()} for fold in self.folds
            ]
            + [self.final_embargo.as_dict()],
            "direct_experiment_integration": {
                "blocked": True,
                "reason": (
                    "ExperimentArtifact supports a single embargo integer and anonymous "
                    "validation_test_windows; it cannot losslessly represent per-fold "
                    "embargo windows plus the FINAL embargo with explicit VALIDATION vs "
                    "UNTOUCHED_TEST roles. Converge experiment schema before direct use."
                ),
            },
        }

    def selection_universe(self) -> FrozenTrainUniverse:
        """Return the frozen population that selection must use."""
        return self.frozen_train_universe

    def select_train_winner(
        self, *, attestation: SelectionAttestation
    ) -> tuple[ResearchWindowPlan, TrainWinner]:
        """Bind a validated selection attestation; arbitrary winners rejected.

        Returns the updated plan (attestation bound, fingerprint changed) and
        the deeply immutable winner derived from the attestation.
        """
        self._validate_attestation(attestation)
        updated = ResearchWindowPlan(
            schema_version=self.schema_version,
            research_start=self.research_start,
            research_end=self.research_end,
            folds=self.folds,
            final_embargo=self.final_embargo,
            final_test=self.final_test,
            fold_train_days=self.fold_train_days,
            fold_validation_days=self.fold_validation_days,
            fold_step_days=self.fold_step_days,
            fold_embargo_days=self.fold_embargo_days,
            final_test_days=self.final_test_days,
            final_embargo_days=self.final_embargo_days,
            min_observations_per_window=self.min_observations_per_window,
            min_folds=self.min_folds,
            approved_capital_rupees=self.approved_capital_rupees,
            session_policy_id=self.session_policy_id,
            cas_policy_id=self.cas_policy_id,
            cost_claim=self.cost_claim,
            ca_claim=self.ca_claim,
            dataset_fingerprints=self.dataset_fingerprints,
            universe_policy_id=self.universe_policy_id,
            pit_attestations=self.pit_attestations,
            frozen_train_universe=self.frozen_train_universe,
            strategy_definitions=self.strategy_definitions,
            selection_attestation=attestation,
            created_at=self.created_at,
        )
        winner = TrainWinner(
            instrument_key=attestation.winner_instrument,
            strategy_name=attestation.winner_strategy,
            parameters=attestation.winner_parameters,
        )
        return updated, winner

    def authorize_untouched_test(
        self,
        *,
        frozen_universe: FrozenTrainUniverse,
        train_winner: TrainWinner,
    ) -> dict[str, Any]:
        """Authorize FINAL test evaluation. Requires bound valid attestation."""
        if self.selection_attestation is None:
            raise AttestationError("FINAL test requires a bound selection attestation")
        self._validate_attestation(self.selection_attestation)
        if frozen_universe != self.frozen_train_universe:
            raise FrozenUniverseViolationError(
                "FINAL test must receive the full frozen population unchanged"
            )
        attestation = self.selection_attestation
        if (
            train_winner.instrument_key != attestation.winner_instrument
            or train_winner.strategy_name != attestation.winner_strategy
            or tuple(train_winner.parameters) != tuple(attestation.winner_parameters)
        ):
            raise AttestationError("train winner does not match bound selection attestation")
        return {
            "plan_id": self.plan_id,
            "final_test": self.final_test.as_dict(),
            "frozen_train_universe": self.frozen_train_universe.as_dict(),
            "train_winner": train_winner.as_dict(),
            "selection_attestation_fingerprint": attestation.fingerprint(),
            "selection_forbidden": True,
        }

    def check_pit_membership(
        self, *, instrument_key: str, trade_date: date, evidence_as_of: date
    ) -> None:
        """Enforce per-instrument per-date PIT membership against attestations."""
        matches = [item for item in self.pit_attestations if item.instrument_key == instrument_key]
        if not matches:
            raise FrozenUniverseViolationError(f"no PIT attestation for {instrument_key!r}")
        attestation = matches[0]
        if trade_date not in set(attestation.trade_dates):
            raise ResearchWindowError(f"{trade_date.isoformat()} is outside attested PIT dates")
        if evidence_as_of > trade_date:
            raise WindowLeakageError(
                f"PIT membership for {trade_date.isoformat()} cannot use evidence "
                f"as of {evidence_as_of.isoformat()}"
            )
        if (
            evidence_as_of != attestation.evidence_as_of
            and evidence_as_of > attestation.evidence_as_of
        ):
            raise WindowLeakageError("PIT evidence_as_of is newer than attested snapshot")


def compile_repeated_wfo(
    *,
    research_start: date,
    research_end: date,
    trading_dates: tuple[date, ...],
    fold_train_days: int,
    fold_validation_days: int,
    fold_step_days: int,
    fold_embargo_days: int,
    final_test_days: int,
    final_embargo_days: int,
    min_observations_per_window: int,
    min_folds: int,
    approved_capital_rupees: Decimal,
    session_policy_id: str,
    cas_policy_id: str,
    cost_claim: CostEvidenceClaim,
    ca_claim: CorporateActionClaim,
    dataset_fingerprints: Mapping[str, str],
    universe_policy_id: str,
    pit_attestations: tuple[PITMembershipAttestation, ...],
    train_universe_instruments: tuple[str, ...],
    strategy_definitions: tuple[StrategyDefinitionClaim, ...],
    created_at: str | None = None,
) -> ResearchWindowPlan:
    """Compile repeated WFO folds plus a separately untouched FINAL test.

    Fold arithmetic delegates to :mod:`wfo_schedule` (shared with
    ``walk_forward``). The FINAL test region is reserved first; folds are
    generated over the remaining prefix. Every size, step, and minimum is an
    explicit caller input.
    """
    if research_start > research_end:
        raise ResearchWindowError("research_start must be on or before research_end")
    for name, value in (
        ("fold_train_days", fold_train_days),
        ("fold_validation_days", fold_validation_days),
        ("fold_step_days", fold_step_days),
        ("final_test_days", final_test_days),
    ):
        if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
            raise ResearchWindowError(f"{name} must be a positive integer")
    for name, value in (
        ("fold_embargo_days", fold_embargo_days),
        ("final_embargo_days", final_embargo_days),
    ):
        if not isinstance(value, int) or isinstance(value, bool) or value < 0:
            raise ResearchWindowError(f"{name} must be a non-negative integer")
    if (
        not isinstance(min_observations_per_window, int)
        or isinstance(min_observations_per_window, bool)
        or min_observations_per_window <= 0
    ):
        raise ResearchWindowError("min_observations_per_window must be a positive integer")
    if not isinstance(min_folds, int) or isinstance(min_folds, bool) or min_folds < 2:
        raise ResearchWindowError("min_folds must be an integer >= 2 for repeated WFO")
    for name, value in (
        ("fold_train_days", fold_train_days),
        ("fold_validation_days", fold_validation_days),
        ("final_test_days", final_test_days),
    ):
        if value < min_observations_per_window:
            raise WindowTooShortError(
                f"{name}={value} is below min_observations_per_window={min_observations_per_window}"
            )
    if not trading_dates:
        raise WindowTooShortError("trading_dates must not be empty")
    ordered = tuple(trading_dates)
    if tuple(sorted(set(ordered))) != ordered:
        raise ResearchWindowError("trading_dates must be sorted unique dates")
    if ordered[0] != research_start or ordered[-1] != research_end:
        raise ResearchWindowError(
            "trading_dates must exactly span research_start through research_end"
        )
    if len(ordered) < final_test_days + final_embargo_days + 1:
        raise WindowTooShortError("trading dates are too short for FINAL test reservation")

    if not isinstance(approved_capital_rupees, Decimal) or approved_capital_rupees <= Decimal(0):
        raise ResearchWindowError("approved_capital_rupees must be a positive Decimal")
    _require_nonempty_str("session_policy_id", session_policy_id)
    _require_nonempty_str("cas_policy_id", cas_policy_id)
    _require_nonempty_str("universe_policy_id", universe_policy_id)
    if not isinstance(cost_claim, CostEvidenceClaim):
        raise EvidenceClaimError("cost_claim must be a CostEvidenceClaim")
    if not isinstance(ca_claim, CorporateActionClaim):
        raise EvidenceClaimError("ca_claim must be a CorporateActionClaim")
    if not strategy_definitions:
        raise ResearchWindowError("strategy_definitions must not be empty")
    for item in strategy_definitions:
        if not isinstance(item, StrategyDefinitionClaim):
            raise ResearchWindowError(
                "strategy_definitions must be StrategyDefinitionClaim records"
            )
    if not pit_attestations:
        raise ResearchWindowError("pit_attestations must not be empty")
    for item in pit_attestations:
        if not isinstance(item, PITMembershipAttestation):
            raise ResearchWindowError("pit_attestations must be PITMembershipAttestation records")

    dataset_pairs = _canonical_pairs("dataset_fingerprints", dataset_fingerprints)
    frozen_instruments = tuple(sorted(set(train_universe_instruments)))
    if not frozen_instruments or any(not key.strip() for key in frozen_instruments):
        raise FrozenUniverseViolationError(
            "train_universe_instruments must be sorted unique non-empty"
        )
    if tuple(k for k, _ in dataset_pairs) != frozen_instruments:
        raise FrozenUniverseViolationError(
            "dataset instrument keys must exactly equal frozen train universe instruments"
        )
    attestation_keys = tuple(
        item.instrument_key for item in sorted(pit_attestations, key=lambda a: a.instrument_key)
    )
    if attestation_keys != frozen_instruments:
        raise FrozenUniverseViolationError(
            "PIT attestations must cover exactly the frozen population"
        )
    ca_population = tuple(sorted(set(ca_claim.population)))
    if ca_population != frozen_instruments:
        raise FrozenUniverseViolationError(
            "corporate-action claim population must equal frozen population"
        )

    final_test_dates = ordered[len(ordered) - final_test_days :]
    final_embargo_dates = ordered[
        len(ordered) - final_test_days - final_embargo_days : len(ordered) - final_test_days
    ]
    fold_region = ordered[: len(ordered) - final_test_days - final_embargo_days]
    try:
        date_folds = plan_wfo_date_windows(
            fold_region,
            train_trading_days=fold_train_days,
            test_trading_days=fold_validation_days,
            step_trading_days=fold_step_days,
            embargo_trading_days=fold_embargo_days,
        )
    except ValueError as exc:
        raise WindowTooShortError(str(exc)) from exc
    if len(date_folds) < min_folds:
        raise WindowTooShortError(
            f"compiled {len(date_folds)} folds below required min_folds={min_folds}; "
            "a single split cannot masquerade as repeated WFO"
        )

    def _window(role: WindowRole, window_id: str, dates: tuple[date, ...]) -> CompiledWindow:
        if role is WindowRole.EMBARGO and not dates:
            return CompiledWindow(
                role=role, window_id=window_id, start=None, end=None, trading_dates=()
            )
        return CompiledWindow(
            role=role, window_id=window_id, start=dates[0], end=dates[-1], trading_dates=dates
        )

    folds: list[WFOFold] = []
    for date_fold in date_folds:
        train_end_idx = fold_region.index(date_fold.train_dates[0]) + fold_train_days
        embargo_dates = fold_region[train_end_idx : train_end_idx + fold_embargo_days]
        folds.append(
            WFOFold(
                fold_id=f"wfo_fold_{date_fold.window_id:02d}",
                train=_window(
                    WindowRole.TRAIN,
                    f"wfo_fold_{date_fold.window_id:02d}_train",
                    date_fold.train_dates,
                ),
                embargo=_window(
                    WindowRole.EMBARGO, f"wfo_fold_{date_fold.window_id:02d}_embargo", embargo_dates
                ),
                validation=_window(
                    WindowRole.VALIDATION,
                    f"wfo_fold_{date_fold.window_id:02d}_validation",
                    date_fold.test_dates,
                ),
            )
        )

    final_embargo = _window(WindowRole.EMBARGO, "final_embargo_01", final_embargo_dates)
    final_test = _window(WindowRole.UNTOUCHED_TEST, "test_final_untouched_01", final_test_dates)

    selection_union = tuple(
        sorted(
            {
                day
                for fold in folds
                for day in (*fold.train.trading_dates, *fold.validation.trading_dates)
            }
        )
    )
    for attestation in pit_attestations:
        if tuple(attestation.trade_dates) != selection_union:
            raise FrozenUniverseViolationError(
                f"PIT attestation for {attestation.instrument_key!r} must cover exactly "
                "the fold train+validation union"
            )

    ordered_attestations = tuple(sorted(pit_attestations, key=lambda a: a.instrument_key))
    population_fingerprint = derive_population_fingerprint(
        instruments=frozen_instruments,
        universe_policy_id=universe_policy_id,
        pit_attestations=ordered_attestations,
    )
    frozen_as_of = max(selection_union)
    frozen_universe = FrozenTrainUniverse(
        instruments=frozen_instruments,
        universe_policy_id=universe_policy_id,
        population_fingerprint=population_fingerprint,
        frozen_as_of=frozen_as_of,
    )
    if frozen_as_of >= (final_embargo.start or final_test.start):  # type: ignore[operator]
        raise WindowLeakageError("frozen population must predate FINAL regions")

    return ResearchWindowPlan(
        schema_version=SCHEMA_VERSION,
        research_start=research_start,
        research_end=research_end,
        folds=tuple(folds),
        final_embargo=final_embargo,
        final_test=final_test,
        fold_train_days=fold_train_days,
        fold_validation_days=fold_validation_days,
        fold_step_days=fold_step_days,
        fold_embargo_days=fold_embargo_days,
        final_test_days=final_test_days,
        final_embargo_days=final_embargo_days,
        min_observations_per_window=min_observations_per_window,
        min_folds=min_folds,
        approved_capital_rupees=approved_capital_rupees,
        session_policy_id=session_policy_id,
        cas_policy_id=cas_policy_id,
        cost_claim=cost_claim,
        ca_claim=ca_claim,
        dataset_fingerprints=dataset_pairs,
        universe_policy_id=universe_policy_id,
        pit_attestations=ordered_attestations,
        frozen_train_universe=frozen_universe,
        strategy_definitions=tuple(strategy_definitions),
        selection_attestation=None,
        created_at=created_at,
    )
